name: Update README Stats

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README stats
        run: |
          curl -H "Authorization: token ${{ secrets.README_STATS_TOKEN }}" \
          https://github-readme-stats.vercel.app/api?username=aAzulis&show_icons=true&theme=tokyonight \
          -o README-stats.svg
          
          # Optionally copy the file to your README using markdown
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README-stats.svg
          git commit -m "Update stats"
          git push
